{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}-config
  labels:
    {{- include "nginx-proxy-manager.labels" . | nindent 4 }}
data:
  {{- with .Values.config.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}