{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}-postgresql
  labels:
    {{- include "nginx-proxy-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "nginx-proxy-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}