apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}
  labels:
    {{- include "nginx-proxy-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
      {{- if and (eq .Values.service.type "NodePort") .Values.service.httpsNodePort }}
      nodePort: {{ .Values.service.httpsNodePort }}
      {{- end }}
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
      {{- if and (eq .Values.service.type "NodePort") .Values.service.adminNodePort }}
      nodePort: {{ .Values.service.adminNodePort }}
      {{- end }}
  selector:
    {{- include "nginx-proxy-manager.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}-admin
  labels:
    {{- include "nginx-proxy-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: admin
      protocol: TCP
      name: admin
      {{- if and (eq .Values.service.admin.type "NodePort") .Values.service.admin.nodePort }}
      nodePort: {{ .Values.service.admin.nodePort }}
      {{- end }}
  selector:
    {{- include "nginx-proxy-manager.selectorLabels" . | nindent 4 }}
{{- end }}