apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}
  labels:
    {{- include "nginx-proxy-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "nginx-proxy-manager.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}-admin
  labels:
    {{- include "nginx-proxy-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "nginx-proxy-manager.selectorLabels" . | nindent 4 }}
{{- end }}